#!/usr/bin/env python3
"""Making Sense Bali DIY node — v7 BASIC, additive-native (DfAM).

Built to the upgraded outdoor-sensor-enclosure skill. The additive-native moves
over v6: (1) a SHEET-GYROID breathing skin over the sensor zone — a separate
snap-in panel generated by marching cubes (tools/gyroid_panel.py), so one lattice
surface is vent + shade + baffle; (2) product-design craft — lifted feet, a
shadow-gap reveal at the hood line, a radius system; (3) the closure stays a
zero-hardware print-in-place bayonet (no screws/inserts). Weatherproofing by
geometry: hood + drip-lip over the gyroid window, weep hole, ePTFE boss, breathe-
don't-seal. BME680 sits behind the gyroid window with a foil liner + air gap.

This builds the Core/Basic shell with the gyroid WINDOW + recess; the matching
gyroid panel is generated separately. ALL FITS COUPON_TBD_*.
"""
import os
from build123d import *  # noqa: F403

OUT = os.path.join(os.path.dirname(__file__), "..", "v7")
os.makedirs(OUT, exist_ok=True)
REVIEW = os.path.join(OUT, "review"); os.makedirs(REVIEW, exist_ok=True)

COUPON_TBD_SLIDE = 0.30
COUPON_TBD_PILOT_M2 = 1.75
perf_w, perf_h, perf_t = 40.0, 60.0, 1.6
bme_w, bme_h, bme_t = 16.0, 12.5, 3.0

wall = 2.5
back_y = 16.0
back_inner = back_y - wall
HW, HW_IN = 24.0, 21.5
FRONT, FRONT_IN = 24.0, 21.5
fillet_r = 3.0
floor_z = 12.0
body_top = 86.0
perf_back_gap = 4.0
perf_z0 = 18.0
key_x, key_z = 16.0, 60.0
bme_z = 30.0
eave, drip, roof_h = 4.0, 3.0, 16.0
cap_r, cap_window_r, n_lugs = 18.0, 11.0, 3
cap_cy = (FRONT_IN - back_inner) / 2
# gyroid breathing window (front wall, BME680 zone)
win_w, win_h, win_zc = 30.0, 28.0, 32.0
foot_h = 3.0


def largest_solid(x):
    try:
        solids = list(x.solids())
    except (AttributeError, TypeError):
        solids = [s for item in x for s in item.solids()]
    return max(solids, key=lambda s: s.volume)


def yrect(z, y0, y1, w):
    return Pos(0, (y0 + y1) / 2.0, z) * Rectangle(w, (y1 - y0))


# dummies
perf_y0 = -back_inner + perf_back_gap
perfboard = Pos(0, perf_y0, perf_z0) * Box(perf_w, perf_t, perf_h, align=(Align.CENTER, Align.MIN, Align.MIN))
perf_env = Pos(0, perf_y0 + perf_t, perf_z0) * Box(perf_w, 11.0, perf_h, align=(Align.CENTER, Align.MIN, Align.MIN))
bme = Pos(0, perf_y0 + perf_t, bme_z) * Box(bme_w, bme_t + 4, bme_h, align=(Align.CENTER, Align.MIN, Align.CENTER))

# ---- shell ----
body = Pos(0, -back_y, foot_h) * Box(2 * HW, back_y + FRONT, body_top, align=(Align.CENTER, Align.MIN, Align.MIN))
body = fillet(body.edges().filter_by(Axis.Z), fillet_r)
cavity = Pos(0, -back_inner, floor_z - wall + foot_h) * Box(2 * HW_IN, back_inner + FRONT_IN, body_top + 10, align=(Align.CENTER, Align.MIN, Align.MIN))
cavity = fillet(cavity.edges().filter_by(Axis.Z), fillet_r - 1.0)
body = largest_solid(body - cavity)

# lifted feet (craft: body reads as a designed volume, not a brick)
for sx in (-1, 1):
    for fy in (-back_y + 5, FRONT - 5):
        foot = Pos(sx * (HW - 6), fy, 0) * Cylinder(3.5, foot_h, align=(Align.CENTER, Align.CENTER, Align.MIN))
        body = body + foot

# floor + cap opening (raised by foot_h)
fz = floor_z - wall + foot_h
floor_plate = Pos(0, -back_y, fz) * Box(2 * HW, back_y + FRONT, wall, align=(Align.CENTER, Align.MIN, Align.MIN))
floor_plate = fillet(floor_plate.edges().filter_by(Axis.Z), fillet_r)
floor_plate = largest_solid(floor_plate - Pos(0, cap_cy, 0) * Cylinder(cap_r - 3.0, 100, align=(Align.CENTER, Align.CENTER, Align.CENTER)))
body = body + floor_plate

# bayonet cap seat (zero-hardware closure)
cs0 = fz - 6.0
cap_seat = Pos(0, cap_cy, cs0) * Cylinder(cap_r + wall + COUPON_TBD_SLIDE, 6.0, align=(Align.CENTER, Align.CENTER, Align.MIN))
cap_seat = largest_solid(cap_seat - Pos(0, cap_cy, cs0 - 0.1) * Cylinder(cap_r + COUPON_TBD_SLIDE, 6.2, align=(Align.CENTER, Align.CENTER, Align.MIN)))
body = body + cap_seat

# perfboard standoffs
so_dx, so_dz = 16.2, 26.2
perf_cz = perf_z0 + perf_h / 2 + foot_h
for sx in (-1, 1):
    for sz in (-1, 1):
        post = Pos(sx * so_dx, -back_inner, perf_cz + sz * so_dz) * Rot(-90, 0, 0) * Cylinder(3.0, perf_back_gap, align=(Align.CENTER, Align.CENTER, Align.MIN))
        pilot = Pos(sx * so_dx, -back_inner - 0.1, perf_cz + sz * so_dz) * Rot(-90, 0, 0) * Cylinder(COUPON_TBD_PILOT_M2 / 2, perf_back_gap + 4, align=(Align.CENTER, Align.CENTER, Align.MIN))
        body = largest_solid(body + post - pilot)

# keyholes
for sx in (-1, 1):
    kh = Pos(sx * key_x, 0, key_z + foot_h) * Rot(-90, 0, 0) * Cylinder(4.0, 50, align=(Align.CENTER, Align.CENTER, Align.CENTER))
    ks = Pos(sx * key_x, -back_y - 2, key_z + foot_h) * Box(4.0, 10, 10, align=(Align.CENTER, Align.MIN, Align.MIN))
    body = largest_solid(largest_solid(body - kh) - ks)

# GYROID breathing window in the front wall + inside rebate for the snap-in panel
wz = win_zc + foot_h
window = Pos(0, FRONT - wall - 1, wz) * Box(win_w, wall + 3, win_h, align=(Align.CENTER, Align.MIN, Align.CENTER))
body = largest_solid(body - window)
rebate = Pos(0, FRONT - wall - 1.6, wz) * Box(win_w + 4.0, 1.6, win_h + 4.0, align=(Align.CENTER, Align.MIN, Align.CENTER))
body = largest_solid(body - rebate)   # 2 mm ledge the gyroid panel seats against from inside

# USB-C gland chase, bottom
usb = Pos(-10.0, cap_cy, fz + 1.0) * Rot(35, 0, 0) * Cylinder(4.25, wall + 16, align=(Align.CENTER, Align.CENTER, Align.MIN))
body = largest_solid(body - usb)

# weep hole
weep = Pos(0, FRONT_IN - 2.0, floor_z + 0.5 + foot_h) * Rot(55, 0, 0) * Cylinder(1.25, 14, align=(Align.CENTER, Align.CENTER, Align.MIN))
body = largest_solid(body - weep)

# ePTFE membrane boss (leeward side wall)
boss = Pos(HW - 1.0, -2.0, body_top - 20 + foot_h) * Rot(0, 90, 0) * Cylinder(6.0, 2.5, align=(Align.CENTER, Align.CENTER, Align.MIN))
body = body + boss
vent = Pos(HW - 0.5, -2.0, body_top - 20 + foot_h) * Rot(0, 90, 0) * Cylinder(3.2, wall + 4, align=(Align.CENTER, Align.CENTER, Align.MIN))
body = largest_solid(body - vent)

# shadow-gap reveal groove just below the hood (craft)
sg = Pos(0, -back_y, body_top + foot_h - 1.5) * Box(2 * HW + 1, back_y + FRONT + 1, 1.0, align=(Align.CENTER, Align.MIN, Align.MIN))
sg = largest_solid(sg - Pos(0, -back_y - 0.5, body_top + foot_h - 2.5) * Box(2 * HW - 2.0, back_y + FRONT + 2, 3.0, align=(Align.CENTER, Align.MIN, Align.MIN)))
body = largest_solid(body - sg)

# hood with drip-lip curl (sheds rain over the gyroid window)
zb = body_top + foot_h
roof_outer = loft([
    yrect(zb, -back_y, FRONT, 2 * HW),
    yrect(zb + eave, -back_y, FRONT + eave, 2 * HW + 2 * eave),
    Pos(0, (FRONT - back_y) / 2, zb + roof_h) * Rectangle(14.0, 12.0),
], ruled=True)
roof_inner = loft([
    yrect(zb - 0.1, -back_inner, FRONT_IN, 2 * HW_IN),
    yrect(zb + eave, -back_inner, FRONT_IN, 2 * HW_IN),
    Pos(0, (FRONT_IN - back_inner) / 2, zb + roof_h - wall) * Rectangle(7.0, 6.0),
], ruled=True)
roof = largest_solid(roof_outer - roof_inner)
lip = Pos(0, -back_y, zb + eave - drip) * Box(2 * (HW + eave), back_y + FRONT + eave, drip, align=(Align.CENTER, Align.MIN, Align.MIN))
lip = largest_solid(lip - Pos(0, -back_y - 1, zb + eave - drip - 1) * Box(2 * (HW + eave) - 3.0, back_y + FRONT + eave, drip + 3, align=(Align.CENTER, Align.MIN, Align.MIN)))
roof = roof + lip
roof = largest_solid(roof - (Pos(0, -back_y, 0) * Box(500, 400, 500, align=(Align.CENTER, Align.MAX, Align.CENTER))))
body = body + roof

# cap (zero-hardware bayonet, down mesh intake)
cap = Cylinder(cap_r, 3.0, align=(Align.CENTER, Align.CENTER, Align.MIN))
cap = cap + Cylinder(cap_r + 4.0, 1.6, align=(Align.CENTER, Align.CENTER, Align.MIN))
stem = Pos(0, 0, 3.0) * Cylinder(cap_r, 7.0, align=(Align.CENTER, Align.CENTER, Align.MIN))
stem = largest_solid(stem - Pos(0, 0, 2.9) * Cylinder(cap_r - wall, 7.2, align=(Align.CENTER, Align.CENTER, Align.MIN)))
cap = cap + stem
for k in range(n_lugs):
    cap = cap + Pos(0, 0, 7.6) * Rot(0, 0, k * 120) * (Pos(cap_r + 1.2, 0, 0) * Box(2.4, 8.0, 2.4, align=(Align.CENTER, Align.CENTER, Align.MIN)))
cap = largest_solid(cap - Cylinder(cap_window_r, 30, align=(Align.CENTER, Align.CENTER, Align.CENTER)))
seat = Pos(0, 0, 3.0) * Cylinder(cap_window_r + 3.0, 1.2, align=(Align.CENTER, Align.CENTER, Align.MIN))
seat = largest_solid(seat - Cylinder(cap_window_r - 1.5, 30, align=(Align.CENTER, Align.CENTER, Align.CENTER)))
cap = cap + seat
for k in range(n_lugs):
    entry = Pos(0, cap_cy, 0) * Rot(0, 0, k * 120) * (Pos(cap_r + 1.2, 0, cs0 - 0.2) * Box(3.4, 9.0, 6.5, align=(Align.CENTER, Align.CENTER, Align.MIN)))
    turn = Pos(0, cap_cy, 0) * Rot(0, 0, k * 120) * (Pos(cap_r + 1.2, 0, cs0 + 2.6) * Box(3.4, 22.0, 3.2, align=(Align.CENTER, Align.MIN, Align.MIN)))
    body = largest_solid(largest_solid(body - entry) - turn)

# interference + exports
def chk(nm, a, b, lim=0.02):
    v = 0.0
    try:
        v = sum(s.volume for s in (a & b).solids()) / 1000.0
    except Exception:
        pass
    print(f"  [{'OK ' if v <= lim else 'FAIL'}] {nm}: {v:.3f} cm3"); return v <= lim


print("=== v7 basic interference ===")
chk("boards vs body", perfboard + perf_env, body)
chk("bme vs body", bme, body)
cap_placed = Pos(0, cap_cy, cs0 - 1.6) * cap
assembly = Compound([body, cap_placed, perfboard, bme])
hh = Pos(0, -back_y, 0) * Box(300, 300, 400, align=(Align.MAX, Align.CENTER, Align.MIN))
cutaway = Compound([largest_solid(body - hh), perfboard, bme])
for nm, part, outdir, step in [("v7_basic_body", body, OUT, True), ("v7_basic_cap", cap, OUT, True),
                                ("v7_basic_assembly", assembly, REVIEW, False), ("v7_basic_cutaway", cutaway, REVIEW, False)]:
    export_stl(part, os.path.join(outdir, f"{nm}.stl"))
    if step:
        export_step(part, os.path.join(outdir, f"{nm}.step"))
    bb = part.bounding_box(); print(f"  {nm}: {bb.size.X:.0f} x {bb.size.Y:.0f} x {bb.size.Z:.0f} mm")
# emit window size so the gyroid panel matches
print(f"  WINDOW {win_w} x {win_h} at z={win_zc+foot_h}, rebate +4 (panel target {win_w+3.6} x {win_h+3.6} x 8)")
